### ISSUE TITLE
C source files do not get parsed

### ISSUE THREAD

**Issue by teeheee** [itsallcode/openfasttrace#240]
# Description
files with .c ending get ignored when parsing for tags

## Steps to Reproduce
```console
echo "req~test~1" > test.md
echo "impl~test~1" > test.c
oft trace -o html -f report.html
```
[test.zip](https://github.com/itsallcode/openfasttrace/files/4510511/test.zip)

## Expected behavior
report.html should include req and impl but only req is listed

# Environment
- OFT: 2.3.5
- OS: Windows 10
- Java Version: openjdk 14 2020-03-17

## Additional context

I started using openfasttrace this day so maybe I missed something in the documentation.

**Comment by redcatbear** [comment]
Perfect timing for this issue. With #239 we added a lot of default extensions for popular programming languages in OFT. Checkout the [release 3.0.0](https://github.com/itsallcode/openfasttrace/releases/tag/3.0.0) we just published and let me know, if that works for you.

**Comment by redcatbear** [comment]
Duplicate of #239.

**Comment by teeheee** [comment]
I just tested the new release and the issue is still present in 3.0.0.

**Comment by kaklakariada** [comment]
I added a system test for this case: #244 and it seems to work. Is it possible that you use the wrong format for referencing the requirement in the source code? It should look like this:

test.md:
```markdown
## C
`req~my-requirement~1`
Needs: impl
```
test.c:
```c
// [impl->req~my-requirement~1]
```

**Comment by redcatbear** [comment]
@teeheee, please make sure you don't forget the **square brackets** in the tags. Can you please re-test and give us feedback if that fixes your problems?

As @kaklakariada wrote, implementation files must have tags in the comments that are wrapped in square brackets, contain the artifact type of the file they are in (e.g. `impl`), an arrow `->` and the ID of the covered requirement.

**Comment by redcatbear** [comment]
Also check for the necessary format needed in requirement documents (i.e. Markdown files). The user guide contains a lot of examples.

**Comment by teeheee** [comment]
Hi, thanks for the tip. Now it is working. Is there a concept behind when to use  [impl->*] notation and when to use the other one?

**Comment by redcatbear** [comment]
The reasons for the notation are:
1. It must be something that has a close to zero chance to appear in regular source code (that's why we added the brackets around it).
1. It can be parsed in a fast and simple way.
1. It must be human readable (read as "this piece of implementation covers the requirement with that ID")
1. It allows mixing multiple artifact types in one single document / file.
2. Since the name of the original ID that is covered is completely intact, you can `grep` over your complete code base to find the occurrences in all documents and code pieces, that helps debugging tracing links.
